const components = [
  {
    id: "comp-019",
    name: "ESP32-CAM",
    short: "ESP32 Camera Module",
    price: 3000,
    currency: "DZD",
    condition: "B",
    stock: 1,
    category: "microcontrollers",
    tags: ["ESP32", "camera"],
    image: "esp32 cam.jpg",
    datasheets: ["https://media.digikey.com/pdf/Data%20Sheets/DFRobot%20PDFs/DFR0602_Web.pdf"],
    compatibility: ["Arduino IDE", "MicroPython", "ESP-IDF"]
  },
  {
    id: "comp-016",
    name: "Bluetooth Audio Receiver Board",
    short: "Bluetooth Module receive music and play it from pins directly or jack port 'Stereo'",
    price: 1200,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "modules",
    tags: ["bluetooth", "audio"],
    image: "Bluetooth Audio Receiver Board.jpg",
    datasheets: ["link"],
    compatibility: ["Speakers", "Amplifiers", "Audio systems"]
  },
  {
    id: "comp-015",
    name: "SD Card Module",
    short: "Micro SD Card Reader Module",
    price: 900,
    currency: "DZD",
    condition: "B",
    stock: 1,
    category: "modules",
    tags: ["SD", "storage"],
    image: "sd card modual.jpg",
    datasheets: ["link"],
    compatibility: ["Arduino", "ESP32", "AVR", "ARM"]
  },
  {
    id: "comp-023",
    name: "HC-RS04",
    short: "Ultrasonic Sensor",
    price: 450,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "sensors",
    tags: ["ultrasonic", "sensor"],
    image: "HC-SR04.jpg",
    datasheets: ["https://www.alldatasheet.com/datasheet-pdf/view/1132204/ETC2/HCSR04.html"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi", "STM32"]
  },
  {
    id: "comp-024",
    name: "LCD1602A Screen",
    short: "LCD Display 8*2",
    price: 700,
    currency: "DZD",
    condition: "B",
    stock: 1,
    category: "displays",
    tags: ["LCD", "I2C"],
    image: "i2c-16x2.jpg",
    datasheets: ["https://www.chipcad.hu/letoltes/webadatlapok/ERM1602-6.pdf"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi"]
  },
  {
    id: "comp-025",
    name: "Joystick",
    short: "Analog Joystick Module",
    price: 400,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "modules",
    tags: ["joystick", "analog"],
    image: "joystick.jpg",
    datasheets: ["https://www.handsontec.com/dataspecs/accessory/PS2-Joystick.pdf"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi"]
  },
  {
    id: "comp-026",
    name: "L298N",
    short: "Motor Driver",
    price: 850,
    currency: "DZD",
    condition: "B",
    stock: 1,
    category: "drivers",
    tags: ["motor", "driver"],
    image: "L298n.jpg",
    datasheets: ["https://www.handsontec.com/dataspecs/L298N%20Motor%20Driver.pdf"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi", "STM32"]
  },
  {
    id: "comp-027",
    name: "Microphone Module",
    short: "Sound sensor",
    price: 450,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "sensors",
    tags: ["microphone", "sensor"],
    image: "microphone modual.jpg",
    datasheets: ["https://fabacademy.org/2024/labs/fabc/students/charlotte-vandenbulcke/files/SEN-17-037-Datasheet.pdf"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi"]
  },
  {
    id: "comp-001",
    name: "0A41SKF3ZA",
    short: "IR Distance Sensor",
    price: 1500,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "sensors",
    tags: ["sensor", "IR"],
    image: "0A41SKF3ZA.jpg",
    datasheets: ["https://www.alldatasheet.com/datasheet-pdf/view/506284/SHARP/0A41SK.html"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi", "STM32"]
  },
  {
    id: "comp-002",
    name: "8mm Buttons",
    short: "Tactile push button",
    price: 50,
    currency: "DZD",
    condition: "A",
    stock: 3,
    category: "switches",
    tags: ["button", "tactile"],
    image: "8mm-button.jpg",
    datasheets: ["https://components101.com/switches/push-button"],
    compatibility: ["Arduino", "ESP32", "Breadboard", "PCB"]
  },
  {
    id: "comp-003",
    name: "4 Relay Module",
    short: "4-channel relay",
    price: 1500,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "modules",
    tags: ["relay", "switch"],
    image: "4-relay-module.jpg",
    datasheets: ["https://www.handsontec.com/dataspecs/4Ch-relay.pdf"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi", "PLC"]
  },
  {
    id: "comp-005",
    name: "SN74LS86N",
    short: "Quad XOR Gate IC",
    price: 100,
    currency: "DZD",
    condition: "A",
    stock: 4,
    category: "ICs",
    tags: ["IC", "logic"],
    image: "SN74LS86N.jpg",
    datasheets: ["https://www.alldatasheet.com/datasheet-pdf/view/5744/MOTOROLA/SN74LS86N.html"],
    compatibility: ["Arduino", "Breadboard", "PCB", "TTL Logic"]
  },
  {
    id: "comp-006",
    name: "6V Motor 3kg Max",
    short: "DC Motor low speed hight tork",
    price: 900,
    currency: "DZD",
    condition: "A",
    stock: 2,
    category: "motors",
    tags: ["motor", "DC"],
    image: "6v-motor.jpg",
    datasheets: ["https://www.handsontec.com/dataspecs/GA12-N20.pdf"],
    compatibility: ["L298N", "TB6612FNG", "Motor Shield"]
  },
  {
    id: "comp-007",
    name: "7 Segment",
    short: "7-Segment Display the '.' do not work",
    price: 40,
    currency: "DZD",
    condition: "C",
    stock: 1,
    category: "displays",
    tags: ["display", "7-segment"],
    image: "7-segment.jpg",
    datasheets: ["https://www.alldatasheet.com/datasheet-pdf/view/26429/VISHAY/TDSR315.html"],
    compatibility: ["Arduino", "ESP32", "74HC595 Shift Register"]
  },
  {
    id: "comp-008",
    name: "9V Battery Plug",
    short: "Battery Connector",
    price: 70,
    currency: "DZD",
    condition: "A",
    stock: 2,
    category: "connectors",
    tags: ["battery", "plug"],
    image: "9v batteryplug1.jpg",
    datasheets: ["https://youtu.be/dQw4w9WgXcQ?si=HKef4VTIB-wfXStn"],
    compatibility: ["9V Battery", "Arduino", "Breadboard"]
  },
  {
    id: "comp-009",
    name: "24V Motor",
    short: "DC Motor 24V",
    price: 700,
    currency: "DZD",
    condition: "A",
    stock: 2,
    category: "motors",
    tags: ["motor", "DC"],
    image: "24v motor.jpg",
    datasheets: ["https://engineering.purdue.edu/477grp1/Files/refs/dc775.pdf"],
    compatibility: ["High-voltage driver", "Motor Shield"]
  },
  {
    id: "comp-010",
    name: "220V to 12V Two Output Transfer",
    short: "AC-AC Transfer 220V to 12V",
    price: 500,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "power",
    tags: ["transformer", "AC-DC"],
    image: "220v to 12v 2output.jpg",
    datasheets: ["link"],
    compatibility: ["Rectifier circuits", "Power supplies"]
  },
  {
    id: "comp-011",
    name: "Antenna for ESP32",
    short: "ESP32 WiFi Antenna",
    price: 400,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "modules",
    tags: ["antenna", "ESP32"],
    image: "antena.jpg",
    datasheets: ["link"],
    compatibility: ["ESP32", "ESP8266", "WiFi modules"]
  },
  {
    id: "comp-012",
    name: "Black Buttons",
    short: "Push button",
    price: 50,
    currency: "DZD",
    condition: "A",
    stock: 13,
    category: "switches",
    tags: ["button", "black"],
    image: "black buttons.jpg",
    datasheets: ["https://components101.com/switches/push-button"],
    compatibility: ["Arduino", "ESP32", "Breadboard"]
  },
  {
    id: "comp-013",
    name: "White Buttons",
    short: "Push button",
    price: 50,
    currency: "DZD",
    condition: "A",
    stock: 10,
    category: "switches",
    tags: ["button", "white"],
    image: "white buttons.jpg",
    datasheets: ["https://components101.com/switches/push-button"],
    compatibility: ["Arduino", "ESP32", "Breadboard"]
  },
  {
    id: "comp-014",
    name: "Blue LED",
    short: "Blue LED",
    price: 5,
    currency: "DZD",
    condition: "D",
    stock: 3,
    category: "LEDs",
    tags: ["LED", "blue"],
    image: "blue led.jpg",
    datasheets: ["https://www.tme.eu/Document/e17ac5a5d91f1e843e5681cfa4a5ba4b/HLMP-HG64-VY0DD.pdf"],
    compatibility: ["Arduino", "ESP32", "Any 3.3V/5V circuit"]
  },
  {
    id: "comp-017",
    name: "Buzzer",
    short: "Active Buzzer",
    price: 70,
    currency: "DZD",
    condition: "B",
    stock: 1,
    category: "modules",
    tags: ["buzzer", "sound"],
    image: "buzzer.jpg",
    datasheets: ["link"],
    compatibility: ["Arduino", "ESP32", "Alarm circuits"]
  },
  {
    id: "comp-018",
    name: "Electric Lock",
    short: "5V Electric Lock 5V",
    price: 1000,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "locks",
    tags: ["lock", "electric"],
    image: "electric-lock.jpg",
    datasheets: ["link"],
    compatibility: ["Relay module", "ESP32", "RFID systems"]
  },
  {
    id: "comp-021",
    name: "Green LED",
    short: "Green LED",
    price: 30,
    currency: "DZD",
    condition: "B",
    stock: 13,
    category: "LEDs",
    tags: ["LED", "green"],
    image: "green led.jpg",
    datasheets: ["https://www.tme.eu/Document/e17ac5a5d91f1e843e5681cfa4a5ba4b/HLMP-HG64-VY0DD.pdf"],
    compatibility: ["Arduino", "ESP32", "Any 3.3V/5V circuit"]
  },
  {
    id: "comp-028",
    name: "Microphone 'Phone'",
    short: "i got them from old devices",
    price: 200,
    currency: "DZD",
    condition: "D",
    stock: 9,
    category: "sensors",
    tags: ["microphone", "electret"],
    image: "microphons.jpg",
    datasheets: ["https://cdn.sparkfun.com/datasheets/Sensors/Sound/CEM-C9745JAD462P2.54R.pdf"],
    compatibility: ["Audio circuits", "Amplifier modules", "Arduino"]
  },
  {
    id: "comp-029",
    name: "Motor",
    short: "Generic DC Motor",
    price: 150,
    currency: "DZD",
    condition: "B",
    stock: 4,
    category: "motors",
    tags: ["motor"],
    image: "motor.jpg",
    datasheets: ["https://components101.com/motors/toy-dc-motor"],
    compatibility: ["L298N", "TB6612FNG", "Toy projects"]
  },
  {
    id: "comp-030",
    name: "tb6612FNG Motor Driver",
    short: "Motor Driver Module",
    price: 900,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "drivers",
    tags: ["motor", "driver"],
    image: "tb1688fng.jpg",
    datasheets: ["https://cdn.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf"],
    compatibility: ["Arduino", "ESP32", "Raspberry Pi", "STM32"]
  },
  {
    id: "comp-031",
    name: "Paper Holder Switch",
    short: "Limit Switch",
    price: 30,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "switches",
    tags: ["switch", "limit"],
    image: "old type switch.jpg",
    datasheets: ["link"],
    compatibility: ["Arduino", "3D printers", "CNC", "Robot endstops"]
  },
  {
    id: "comp-032",
    name: "Orange LED",
    short: "Orange LED",
    price: 5,
    currency: "DZD",
    condition: "B",
    stock: 2,
    category: "LEDs",
    tags: ["LED", "orange"],
    image: "orange led.jpg",
    datasheets: ["https://www.tme.eu/Document/e17ac5a5d91f1e843e5681cfa4a5ba4b/HLMP-HG64-VY0DD.pdf"],
    compatibility: ["Arduino", "ESP32", "Any 3.3V/5V circuit"]
  },
  {
    id: "comp-033",
    name: "Speakers 1",
    short: "Audio Speaker",
    price: 300,
    currency: "DZD",
    condition: "B",
    stock: 7,
    category: "audio",
    tags: ["speaker"],
    image: "speaker1.jpg",
    datasheets: ["link"],
    compatibility: ["PAM8403 amplifier", "Audio projects"]
  },
  {
    id: "comp-034",
    name: "Speakers 2",
    short: "Audio Speaker",
    price: 600,
    currency: "DZD",
    condition: "B",
    stock: 3,
    category: "audio",
    tags: ["speaker"],
    image: "speaker2.jpg",
    datasheets: ["link"],
    compatibility: ["PAM8403", "LM386", "Audio amplifiers"]
  },
  {
    id: "comp-035",
    name: "Speakers 3",
    short: "Audio Speaker",
    price: 900,
    currency: "DZD",
    condition: "B",
    stock: 1,
    category: "audio",
    tags: ["speaker"],
    image: "speaker3.jpg",
    datasheets: ["link"],
    compatibility: ["Audio amplifiers", "Bluetooth receivers"]
  },
  {
    id: "comp-036",
    name: "Speakers 4",
    short: "Audio Speaker",
    price: 300,
    currency: "DZD",
    condition: "B",
    stock: 5,
    category: "audio",
    tags: ["speaker"],
    image: "speaker4.jpg",
    datasheets: ["link"],
    compatibility: ["PAM8403 amplifier", "Audio projects"]
  },
  {
    id: "comp-037",
    name: "12-5V Stepper Motor with Driver",
    short: "Stepper Motor Module",
    price: 1000,
    currency: "DZD",
    condition: "A",
    stock: 2,
    category: "motors",
    tags: ["stepper", "driver"],
    image: "steper motor.jpg",
    datasheets: ["https://www.hadex.cz/spec/m513.pdf"],
    compatibility: ["Arduino", "ESP32", "3D printers", "CNC"]
  },
  {
    id: "comp-038",
    name: "Switch On/Off",
    short: "Toggle Switch",
    price: 90,
    currency: "DZD",
    condition: "B",
    stock: 10,
    category: "switches",
    tags: ["switch"],
    image: "switch.jpg",
    datasheets: ["https://components101.com/switches/spdt-toggle-switch"],
    compatibility: ["Arduino", "Breadboard", "DIY projects"]
  },
  {
    id: "comp-039",
    name: "Fancy Switch",
    short: "6 pins switch",
    price: 150,
    currency: "DZD",
    condition: "A",
    stock: 1,
    category: "switches",
    tags: ["switch", "decorative"],
    image: "swithc2.jpg",
    datasheets: ["https://components101.com/switches/spdt-toggle-switch"],
    compatibility: ["DIY projects", "Control panels"]
  },
  {
    id: "comp-040",
    name: "Vibration Motor",
    short: "Vibration Motor",
    price: 200,
    currency: "DZD",
    condition: "B",
    stock: 5,
    category: "motors",
    tags: ["vibration", "motor"],
    image: "vibration_motor.jpg",
    datasheets: ["https://www.mouser.com/datasheet/2/321/28822-Vibration-Motor-Capsule-Documentation-370386.pdf"],
    compatibility: ["Arduino", "ESP32", "Wearables", "Haptic feedback"]
  },
  {
    id: "comp-041",
    name: "White LED",
    short: "White LED 'in datasheet same concept but not same dimensions'",
    price: 5,
    currency: "DZD",
    condition: "B",
    stock: 18,
    category: "LEDs",
    tags: ["LED", "white"],
    image: "white led.jpg",
    datasheets: ["https://www.tme.eu/Document/e17ac5a5d91f1e843e5681cfa4a5ba4b/HLMP-HG64-VY0DD.pdf"],
    compatibility: ["Arduino", "ESP32", "Any 3.3V/5V circuit"]
  },
  {
    id: "comp-042",
    name: "Yellow LED",
    short: "Yellow LED",
    price: 5,
    currency: "DZD",
    condition: "B",
    stock: 15,
    category: "LEDs",
    tags: ["LED", "yellow"],
    image: "yellow led.jpg",
    datasheets: ["https://www.tme.eu/Document/e17ac5a5d91f1e843e5681cfa4a5ba4b/HLMP-HG64-VY0DD.pdf"],
    compatibility: ["Arduino", "ESP32", "Any 3.3V/5V circuit"]
  },
  {
    id: "comp-043",
    name: "12v Motor",
    short: "Generic DC Motor",
    price: 230,
    currency: "DZD",
    condition: "B",
    stock: 2,
    category: "motors",
    tags: ["motor"],
    image: "12V motor.jpg",
    datasheets: ["https://engineering.purdue.edu/477grp1/Files/refs/dc775.pdf"],
    compatibility: ["L298N", "TB6612FNG", "Motor shields"]
  }
];
